### ISSUE TITLE
Obsolete Sinon.JS

### ISSUE THREAD

**Issue by ussuritiger** [vistaprint/grunt-js-test#18]
Plugin uses SinonJS v1.7.1 which is very old and misses some useful stuff like onCall API. Is it possible to update plugin with the new version of SinonJS which is 1.14.1?

**Comment by texclayton** [comment]
Grab the latest using git, delete the npm-shrinkwrap.json file, and run 'npm install'.  That should get you the latest version of Sinon.
Please reply here and let me know how it works out for you.

**Comment by ussuritiger** [comment]
Thanks texclayton, however that did not help. After doing the steps that you described the sinon.js file was not presented in the views/deps folder at all.

Another thing is that I use the grunt-js-test plugin with Jenkins so it is not very handy to do all these steps that you described. Would be much better to install the plugin with the latest stable versions of Chai and Sinon by default.

**Comment by benhutchins** [comment]
@ussuritiger The latest revision in master removed Sinon from views/deps and is using it an npm module dependency instead. You'll see it references in https://github.com/vistaprint/grunt-js-test/blob/master/package.json#L53

This is what master is using, compared to the last npm publish of `grunt-js-test`:
Sinon went from `1.7.1` to `*` (which resolves to `1.14.1` currently)
Chai went from `1.8.0` to `2.3.0`

Mocha also went to this new dependency style, allowing for it to be updated more easily in the future.

**Comment by texclayton** [comment]
I'll be updating the npm package soon with the changes that Benjamin
Hutchins referred to.  Hopefully I'll have it updated by Monday.

**Comment by texclayton** [comment]
The npm package has been updated to 1.5.8.  This includes the newest version of Sinon and Chai.
